Launcher script improved to handle: - capsule trampoline - faster loading - drip launcher

diff --git a/nextflow b/nextflow
--- a/nextflow
+++ b/nextflow
@@ -35,6 +35,11 @@ function echo_yellow() {
     echo -e "$YELLOW$*$NORMAL"
 }
 
+function die() {
+  echo_red "$*"
+  exit 1
+}
+
 function get() {
     if command -v wget &>/dev/null; then
         GET="wget -q $1 -O $2"
@@ -102,21 +107,21 @@ export NXF_HOME
 # Check if it is required to run in background
 bg=''
 declare -a args=("$@")
-action=''
+cmd=''
 while [[ $# != 0 ]]; do
     case $1 in
     -bg)
       bg=1
       ;;
     -download)
-      if [[ ! "$action" ]]; then
+      if [[ ! "$cmd" ]]; then
       rm -rf $NXF_HOME/framework/$NXF_VER || exit $?
       $0 -version || exit $?
       exit 0
       fi
       ;;
     -self-update|self-update)
-      if [[ ! "$action" ]]; then
+      if [[ ! "$cmd" ]]; then
       install $0;
       exit 0
       fi
@@ -137,13 +142,13 @@ while [[ $# != 0 ]]; do
       else NXF_DRMAA='us.levk:drmaa-gridengine:6.2u5'; fi
       ;;
     *)
-      [[ $1 && $1 != -* && ! "$action" ]] && action=$1
+      [[ $1 && $1 != -* && ! "$cmd" ]] && cmd=$1
       ;;
     esac
     shift
 done
 
-[[ "$action" == "node" && ! "$NXF_PACKAGE" ]] && NXF_PACKAGE='gg'
+[[ "$cmd" == "node" && ! "$NXF_PACKAGE" ]] && NXF_PACKAGE='gg'
 
 NXF_PACKAGE=${NXF_PACKAGE:-one}
 NXF_JAR=${NXF_JAR:-nextflow-$NXF_VER-$NXF_PACKAGE.jar}
@@ -151,23 +156,37 @@ NXF_BIN=${NXF_BIN:-$NXF_HOME/framework/$NXF_VER/$NXF_JAR}
 NXF_BASE=${NXF_BASE:-http://www.nextflow.io/releases}
 NXF_PATH=$(dirname $NXF_BIN)
 NXF_URL=${NXF_URL:-$NXF_BASE/v$NXF_VER/$NXF_JAR}
-NXF_DEPS=${NXF_DEPS:-''}
+NXF_GRAB=${NXF_GRAB:-''}
 NXF_CLASSPATH=${NXF_CLASSPATH:-''}
 
 # define the path when dependencies jars will be extracted
 export CAPSULE_CACHE_DIR=${CAPSULE_CACHE_DIR:=$NXF_HOME/capsule}
 CAPSULE_LOG=${CAPSULE_LOG:-'none'}
 
-# Find out installed JDK
-JAVA=java
-[[ -n "$JAVA_HOME" ]] && JAVA="$JAVA_HOME/bin/java"
+# Determine the Java command to use to start the JVM.
+if [ -z "$JAVA_CMD" ] ; then
+    if [ -n "$JAVA_HOME" ] ; then
+        if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+            # IBM's JDK on AIX uses strange locations for the executables
+            JAVA_CMD="$JAVA_HOME/jre/sh/java"
+        else
+            JAVA_CMD="$JAVA_HOME/bin/java"
+        fi
+    else
+        JAVA_CMD="`which java`"
+    fi
+fi
+if [ ! -x "$JAVA_CMD" ] ; then
+    die "Nextflow cannot start -- unable to run Java executable: $JAVA_CMD"
+fi
+
 
 # Verify installed Java version
-if [ ! -f "$NXF_BIN" ]; then
-    $JAVA -version 2>&1 | awk '/version/ {print $3}' | grep '"1\.[7|8]\..*"' > /dev/null
+if [ ! -f "$NXF_BIN" ]; then # <-- only the first time
+    $JAVA_CMD -version 2>&1 | awk '/version/ {print $3}' | grep '"1\.[7|8]\..*"' > /dev/null
     if [ $? -ne 0 ]; then
          echo_red "Error: cannot find Java or it's a wrong version -- please make sure that Java 7 or higher it's installed"
-         [ "$JAVA_HOME" ] && echo_red "Note : nextflow is trying to use the Java VM whose installation path is defined by the variable JAVA_HOME = $JAVA_HOME\n"
+         echo_red "Note: Nextflow is trying to use the Java VM defined by the following environment variables:\n JAVA_CMD: $JAVA_CMD\n JAVA_HOME: $JAVA_HOME\n"
          exit 1
     fi
 
@@ -178,7 +197,7 @@ fi
 check=".+:.+:.+"
 if [[ "$NXF_DRMAA" =~ $check ]]; then
   # add drmaa library downloadable from maven to dependencies list
-  NXF_DEPS+=" $NXF_DRMAA"
+  NXF_GRAB+=" $NXF_DRMAA"
 elif [[ "$NXF_DRMAA" && -f "$NXF_DRMAA" ]]; then
   # add drmaa jar file to custom classpath
   NXF_CLASSPATH+=":$NXF_DRMAA"
@@ -188,22 +207,27 @@ elif [[ "$NXF_DRMAA" ]]; then
 fi
 
 COLUMNS=${COLUMNS:-`tput cols 2> /dev/tty || true`}
-JVM_OPTS="-noverify -Djava.awt.headless=true -Dcapsule.log=$CAPSULE_LOG"
-[[ "$NXF_OPTIONS" ]] && JVM_OPTS+=" $NXF_OPTIONS"
+JAVA_OPTS="-noverify -Djava.awt.headless=true -Dcapsule.log=$CAPSULE_LOG -Dcapsule.trampoline"
+[[ "$JAVA_HOME" ]] && JAVA_OPTS+=" -Dcapsule.java.home=$JAVA_HOME"
+[[ "$cmd" != "run" && "$cmd" != "node" ]] && JAVA_OPTS+=" -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
+[[ "$NXF_OPTS" ]] && JAVA_OPTS+=" $NXF_OPTS"
 [[ "$NXF_CLASSPATH" ]] && export NXF_CLASSPATH
-[[ "$NXF_DEPS" ]] && export NXF_DEPS
+[[ "$NXF_GRAB" ]] && export NXF_GRAB
 [[ "$COLUMNS" ]] && export COLUMNS
+# use drip to speedup startup time -- https://github.com/ninjudd/drip
+[[ "$NXF_DRIP" ]] && export DRIP_INIT='' && export DRIP_INIT_CLASS='nextflow.cli.DripMain'
+export JAVA_CMD
 
 # Start in daemon mode
 if [[ "$bg" ]]; then
   NXF_PID_FILE=${NXF_PID_FILE:-'.nextflow.pid'}
-  "$JAVA" $JVM_OPTS -jar "$NXF_BIN" "${args[@]}" &
+  `"$JAVA_CMD" $JAVA_OPTS -jar "$NXF_BIN"` "${args[@]}" &
   disown
   printf $! > $NXF_PID_FILE
   exit 0
 fi
 
-exec "$JAVA" $JVM_OPTS -jar "$NXF_BIN" "${args[@]}"
+exec `"$JAVA_CMD" $JAVA_OPTS -jar "$NXF_BIN"` "${args[@]}"
 exit 1
 
 
